default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: proxy_crawl_development
  host: <%= Rails.application.credentials[:database][:development][:master][:host] %>
  username: <%= Rails.application.credentials[:database][:development][:master][:username] %>
  password: <%= Rails.application.credentials[:database][:development][:master][:password] %>

test:
  <<: *default
  database: proxy_crawl_test
  host: <%= Rails.application.credentials[:database][:test][:master][:host] %>
  username: <%= Rails.application.credentials[:database][:test][:master][:username] %>
  password: <%= Rails.application.credentials[:database][:test][:master][:password] %>
